"""
Project Euler Problem #2
=========================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

sum = 0
a = 1
b = 2

while True:
    if b > 4000000:
        break
    if b % 2 == 0:
        sum += b

    # Calculate next number in the sequence
    a,b = b,a
    b += a

print(sum)
